{% set version = "0.2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-r2d3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/r2d3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/r2d3/r2d3_{{ version }}.tar.gz
  sha256: b90cf02875e4d974c760d70f5edd39f5481b6c314cfdb76e1cc080acb987b796

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets >=1.2
    - r-jsonlite
    - r-rstudioapi
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets >=1.2
    - r-jsonlite
    - r-rstudioapi

test:
  commands:
    - $R -e "library('r2d3')"           # [not win]
    - "\"%R%\" -e \"library('r2d3')\""  # [win]

about:
  home: https://github.com/rstudio/r2d3
  license: BSD-3-Clause
  summary: Suite of tools for using 'D3', a library for producing dynamic, interactive data visualizations. Supports translating objects into 'D3' friendly data structures, rendering 'D3' scripts, publishing 'D3' visualizations, incorporating 'D3' in R Markdown, creating interactive 'D3' applications with Shiny, and distributing
    'D3' based 'htmlwidgets' in R packages.
  license_family: BSD

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r

# Package: r2d3
# Type: Package
# Title: Interface to 'D3' Visualizations
# Version: 0.2.3
# Authors@R: c( person("Javier", "Luraschi", email = "javier@rstudio.com", role = c("aut", "cre")), person("JJ", "Allaire", role = c("aut")), person("Mike", "Bostock", role = c("ctb", "cph"), comment = "d3.js library, http://d3js.org"), person(family = "RStudio", role = c("cph")) )
# Maintainer: Javier Luraschi <javier@rstudio.com>
# Description: Suite of tools for using 'D3', a library for producing dynamic, interactive data visualizations. Supports translating objects into 'D3' friendly data structures, rendering 'D3' scripts, publishing 'D3' visualizations, incorporating 'D3' in R Markdown, creating interactive 'D3' applications with Shiny, and distributing 'D3' based 'htmlwidgets' in R packages.
# License: BSD_3_clause + file LICENSE
# Encoding: UTF-8
# LazyData: TRUE
# Depends: R (>= 3.1.2)
# Imports: htmlwidgets (>= 1.2), htmltools, jsonlite, rstudioapi
# Suggests: knitr, rmarkdown, shiny, shinytest, testthat, webshot
# RoxygenNote: 6.0.1
# URL: https://github.com/rstudio/r2d3
# BugReports: https://github.com/rstudio/r2d3/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-12-18 23:21:31 UTC; javierluraschi
# Author: Javier Luraschi [aut, cre], JJ Allaire [aut], Mike Bostock [ctb, cph] (d3.js library, http://d3js.org), RStudio [cph]
# Repository: CRAN
# Date/Publication: 2018-12-18 23:50:03 UTC
