appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pSKy6lPKY3GvmISAsSeKDq9cPy9BBxFeHWu6QTRQmc8qOq8M0t3fG66FE0UFrvSGLbi/vsjFUrpcNhWY35ZsyWwBJi7nTrX+AfEMW86b0t1Mm/UhLmGj9Wgh4bm7EkluWzdSdRx7ho0mMzN+ZogACQwRrRK/T8ljKtkXjc5IJcrUryIF4TUmLlH3053JDummYY2k6UnwN/+Wq/5QtiulRDRqhfOceeD6XMAqR2KtxFSmpTSy9SNNURJ2cS2p6piolIqlX6Lgtxus1YacepDkJOqk66koVbczkOK7qe/m2rGv0jr1zcQZn/nJPNJqfAP9GucnapUTzHiALa97qTOuXB22YawPnBd3Y7p2ZRUp0M60AOgsEiR3OE6ECz0WD9KSGBji/yh0Xy7zjfCh6Vr/TF2Jz+y6FJ4yUe+Pe1JraA2V9BA17SshbBbPATzeRburxnw48gh5q09CIpVka93B1oS05Q8LdEv4rkNc2TBRSXXfnVzs2VwzvZGG4QZ6ano967XE1YTH2AWc31nzv9VT6D+udVDJD8bbSnBZ7G4zX5QhUQWaPW3dVgEmur+sd/QK8dCfK98toBqy87d03/y1vTLeU/bNoa3rxlv97iKXNK+xHebVw/+VpvJ22YMNlFTQhV7qAZkkWSNoRUROwAXZJmilye+agl++4JwnBAMvGfg=
conda_forge_output_validation: true
